name: Terraform Apply on Lambda Update

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Zip changed Lambda scripts
        id: zip
        run: |
          mkdir -p zipped
          changed_files=$(git diff --name-only HEAD~1 HEAD | grep '^scripts/.*\.py$' || true)
          if [ -z "$changed_files" ]; then
            echo "No Python scripts changed in last commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            for file in $changed_files; do
              fname=$(basename "$file" .py)
              zip -j "zipped/${fname}.zip" "$file"
              echo "Zipped $file"
            done
            echo "changed=true" >> $GITHUB_OUTPUT

      - name: Upload ZIPs to S3
        if: steps.zip.outputs.changed == 'true'
        run: |
          for zipfile in zipped/*.zip; do
            aws s3 cp "$zipfile" "s3://lambda-artifacts-ziad/lambda/$(basename $zipfile)"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: test
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        if: steps.zip.outputs.changed == 'true'
        working-directory: test
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
